<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407233819 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE property (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, price NUMERIC(10, 2) NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8BF21CDE9D86650F ON property (user_id_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE visit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id_id INT DEFAULT NULL, client_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_437EE939B9575F5A ON visit (property_id_id)');
        $this->addSql('CREATE INDEX IDX_437EE939DC2902E0 ON visit (client_id_id)');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE visit ADD CONSTRAINT FK_437EE939B9575F5A FOREIGN KEY (property_id_id) REFERENCES property (id)');
        $this->addSql('ALTER TABLE visit ADD CONSTRAINT FK_437EE939DC2902E0 FOREIGN KEY (client_id_id) REFERENCES client (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE property DROP CONSTRAINT FK_8BF21CDE9D86650F');
        $this->addSql('ALTER TABLE visit DROP CONSTRAINT FK_437EE939B9575F5A');
        $this->addSql('ALTER TABLE visit DROP CONSTRAINT FK_437EE939DC2902E0');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE property');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE visit');
    }
}
