<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407235021 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE property_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, set_order INT DEFAULT NULL, alt_text VARCHAR(255) DEFAULT NULL, property_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_32EC552B9575F5A ON property_image (property_id_id)');
        $this->addSql('ALTER TABLE property_image ADD CONSTRAINT FK_32EC552B9575F5A FOREIGN KEY (property_id_id) REFERENCES property (id)');
        $this->addSql('ALTER TABLE property ADD slug VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE property ADD content TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE property ADD is_published BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE property ADD main_image VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE property_image DROP CONSTRAINT FK_32EC552B9575F5A');
        $this->addSql('DROP TABLE property_image');
        $this->addSql('ALTER TABLE property DROP slug');
        $this->addSql('ALTER TABLE property DROP content');
        $this->addSql('ALTER TABLE property DROP is_published');
        $this->addSql('ALTER TABLE property DROP main_image');
    }
}
